# Generated by Django 5.2.1 on 2025-05-19 22:59

import register.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[register.validator.validate_username])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200, validators=[register.validator.validate_password])),
                ('confirmation', models.CharField(max_length=140)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('n-b', 'Non-binary'), ('o', 'Other'), ('p', 'Prefer not to say')], max_length=3)),
                ('birthdate', models.DateField(validators=[register.validator.validate_birthdate])),
                ('phone', models.CharField(max_length=19, validators=[register.validator.validate_phone])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
